### ISSUE TITLE
routers 里的go 文件是不是修改了啊

### ISSUE THREAD

**Issue by songoow** [Terry-Ye/im_api#1]
你好，我在实现这个demo的时候，发现routers 里面的有一个路由是指向im/web ,是不是im 里面的文件已经修改，这个demo 目前实现不了？

**Comment by Terry-Ye** [comment]
抱歉，我并没有看到有im_api 这里有路由指定im/web的路由，你可以具体说说你遇到问题的文件或地方么？

**Comment by songoow** [comment]
谢谢，我用这个新的替换了老的im_api,配置好了数据库 ,然后部署了im 安装comet、logic、job模块
在im_api 项目路径下 bee run ，
2019/03/08 13:03:49 INFO     ▶ 0001 Using 'im_api' as 'appname'
2019/03/08 13:03:49 INFO     ▶ 0002 Initializing watcher...
2019/03/08 13:03:52 SUCCESS  ▶ 0003 Built Successfully!
2019/03/08 13:03:52 INFO     ▶ 0004 Restarting 'im_api'...
2019/03/08 13:03:52 SUCCESS  ▶ 0005 './im_api' is running...
2019/03/08 13:03:52.733 [I] [router.go:271]  /Users/song/go/src/im_api/controllers no changed
2019/03/08 13:03:52.734 [I] [router.go:271]  /Users/song/go/src/im_api/controllers/user no changed
2019/03/08 13:03:52.740 [I] [asm_amd64.s:1333]  http server Running on http://:8081
2019/03/08 13:03:52.742 [I] [asm_amd64.s:1333]  https server Running on https://:8080
2019/03/08 13:03:52.742 [C] [asm_amd64.s:1333]  ListenAndServeTLS:  open : no such file or directory

新出现的错误是
ListenAndServeTLS:  open : no such file or directory。
项目路径下面多出了一个临时文件lastupdate.tmp   这样该如何解决

**Comment by Terry-Ye** [comment]
ListenAndServeTLS 是使用https协议的，如果是你使用https，需要在app.conf 配置参数 
`
HTTPSCertFile='证书的文件地址'
`
`
HTTPSKeyFile='证书的文件地址'
`

假设你不想使用https ,请把 conf/app.conf 中的配置成
`
EnableHTTPS = flase
`
`
EnableHttpTLS = flase
`

试试看

**Comment by songoow** [comment]
谢谢，我现在bee run出来的页面是404 ，可能是其他问题，我周末再仔细看下，
祝周末愉快

**Comment by Terry-Ye** [comment]
好的，bee run 后看你配置文件app.conf 配置的端口，周末愉快

**Comment by songoow** [comment]
新手，不好意思又来打扰了，端口设置了，数据库相关的应该都没错，我想实现https://www.texixi.com:1999/ 这个demo，在im_api 中bee run 后，访问8080 端口，出来的是beego 页面的NOT FOUND。在im/demo/main.go 中运行的是
log.Fatal(http.ListenAndServe(":1999", http.FileServer(http.Dir("./"))))，这个main.go 里面是不是代码缺失啊，

**Comment by Terry-Ye** [comment]
sorry， 我在文档少写了一个步骤， 你看回 https://github.com/Terry-Ye/im 项目， 
// demo页面执行
`cd $GOPATH/src/im/demo`
`go run main.go`

im_api 这个项目都是用户相关的api.

**Comment by anotheros** [comment]
bee run 所有页面都是404
